### ISSUE TITLE
How do you deal with double insulation?

### ISSUE THREAD

**Issue by KowalskiThomas** [Here-Be-Dragons/familamp#5]
Hey!
I'm kind of trying to do something similar to what you did, though I'm dealing with a problem I don't really know how to solve... And I think you should have met it too.
I purchased a power supply to... power my lamp you know, though it's double insulated, so as long as I use my capacitive sensor while plugged to my computer, everything goes right, but as soon as I unplug the microcontroller from the computer, the common ground is lost, hence the capacitive sensor doesn't work (since my ground is not the same as the controller's one). Have you dealt with that and, if so, how?
Thank you :)

**Comment by Here-Be-Dragons** [comment]
Best I can tell all 5VDC power supplies are double insulated.  I do know that a high-quality supply is recommended by the various capacitive sensing articles I've read, to reduce noise and get a more accurate reading from the sensor, but I've had luck even from low-quality adapters.  UL-listed adapters seem to be a good idea to look for.  However, I don't believe a common ground is necessary, as I seem to recall I was able to successfully run the lamp from a portable battery pack (though I may be incorrect, I'll have to test this later and report back.)  If you're using the Particle Photon like I did, you can try using a high-quality Smartphone plug.  If it doesn't have the output rating you need, just adjust the sketch to use fewer LEDs.

If none of that is helpful, mind posting a schematic of your design?

**Comment by KowalskiThomas** [comment]
I'm not using a Particle Photon (for various reasons, the first one being the price that was simply out of my means) but a NodeMCU, wired to a ProMicro for the capacitive sensing (that may seem weird, but the NodeMCU on its own can't make the capacitive sensing work. Seems like I'm not the first one facing this issue on the NodeMCU, and no one could sort it out) I'm using the semi-official Arduino CapacitiveSensor library. 

I've tried to make the sensor work with various adapters (a Samsung one, an Apple one, my OnePlus 4A adapter, and finally a random Chinese one I had on my hands) and none of them allowed the capacitive sensor to work while not connected to the computer. Though, as expected, as soon as I draw a wire from the ground to something as a home appliance, the capacitive sensor works correctly... 

I'll send a schematic, but since I'm not home right now it will wait a bit.

**Comment by Here-Be-Dragons** [comment]
Confirmed that the touch does not work on a USB battery pack, so a ground is needed.  My implementation works using pretty much any AC->DC wall wart, though, so it is getting a grounded connection through the Neutral wire in the wall.

**Comment by Here-Be-Dragons** [comment]
@KowalskiThomas Another user on the Particle Forums was having a similar issue and it appears to have been an incompatible resistor value for the sensing circuit.  Moving from 10MOhm to 1MOhm resolved their particular issue.  Can you play with increasing and decreasing the resistor on the touch circuit and see if it helps?

Related post: https://community.particle.io/t/familamp-cloud-synchronized-color-selectable-lamps/28589/30

**Comment by KowalskiThomas** [comment]
Well, I randomly added a 100 pF (in series with the 1 MOhm resistor I already had) and now it's working. Can't explain it but as long as it works, it's none of my business.

**Comment by Here-Be-Dragons** [comment]
Glad to hear.  If you end up with a finished product I'd love to see what you've made.  I'm closing this issue.
